services:
    mongo1:
        image: mongo:latest
        container_name: mongo1
        command: ['--replSet', 'rs0', '--bind_ip_all']
        ports:
            - 27017:27017
        volumes:
            - mongo_data1:/data/db
    mongo2:
        image: mongo:latest
        container_name: mongo2
        command: ['--replSet', 'rs0', '--bind_ip_all']
        ports:
            - 27018:27017
        volumes:
            - mongo_data2:/data/db
volumes:
    mongo_data1:
    mongo_data2:
